#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct  5 11:55:44 2020

@author: alucard
"""

print("General Kenobi : Hello There!!!")
print("Grevius : General Kenobi!!!!!")
print("Hello There again!!")
print("Hello again")